/* eslint-disable */
// AUTO-GENERATED — DO NOT EDIT BY HAND
// source: data/flashcards.csv
// generated by: node scripts/generate_flashcards_from_csv.mjs

export type LangKey = "yo" | "ig" | "pg";

export type FlashcardCategory =
  | "greetings"
  | "family"
  | "food"
  | "school"
  | "numbers"
  | "colors"
  | "actions"
  | "travel"
  | "health"
  | "polite";

export type Flashcard = {
  id: number;

  // keep these keys for app compatibility
  en: string;
  yo: string;
  ig: string;
  pg: string;

  category: FlashcardCategory;
  difficulty: 1 | 2 | 3;
  tags?: string[];
  notes?: {
    yo?: string;
    ig?: string;
    pg?: string;
  };
  synonyms?: Partial<Record<LangKey, string[]>>;
};

export const flashcards: Flashcard[] = [
  {
    id: 1,
    en: `hello`,
    yo: `báwo`,
    ig: `ndewo`,
    pg: `how far`,
    category: "greetings",
    difficulty: 1, tags: ["daily","kids"], notes: {"yo":"also: 'ẹ n lẹ' (formal)"},
  },
  {
    id: 2,
    en: `good morning`,
    yo: `ẹ káàrọ̀`,
    ig: `ụtụtụ ọma`,
    pg: `good morning`,
    category: "greetings",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 3,
    en: `good afternoon`,
    yo: `ẹ káàsán`,
    ig: `ehihie ọma`,
    pg: `good afternoon`,
    category: "greetings",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 4,
    en: `good evening`,
    yo: `ẹ kúalẹ́`,
    ig: `mgbede ọma`,
    pg: `good evening`,
    category: "greetings",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 5,
    en: `how are you?`,
    yo: `ṣé àlàáfíà ni?`,
    ig: `kedu ka i mere?`,
    pg: `how you dey?`,
    category: "greetings",
    difficulty: 2, tags: ["daily"],
  },
  {
    id: 6,
    en: `thank you`,
    yo: `ẹ ṣé`,
    ig: `daalụ`,
    pg: `thank you`,
    category: "polite",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 7,
    en: `please`,
    yo: `jọ̀wọ́`,
    ig: `biko`,
    pg: `abeg`,
    category: "polite",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 8,
    en: `sorry`,
    yo: `má bínú`,
    ig: `ndo`,
    pg: `sorry`,
    category: "polite",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 9,
    en: `family`,
    yo: `ẹbí`,
    ig: `ezinụlọ`,
    pg: `family`,
    category: "family",
    difficulty: 1, tags: ["kids"], notes: {"yo":"tone marks matter"},
  },
  {
    id: 10,
    en: `mother`,
    yo: `ìyá`,
    ig: `nne`,
    pg: `mama`,
    category: "family",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 11,
    en: `father`,
    yo: `bàbá`,
    ig: `nna`,
    pg: `papa`,
    category: "family",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 12,
    en: `child`,
    yo: `ọmọ`,
    ig: `nwa`,
    pg: `pikin`,
    category: "family",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 13,
    en: `food`,
    yo: `oúnjẹ`,
    ig: `nri`,
    pg: `food`,
    category: "food",
    difficulty: 1, tags: ["daily","kids"],
  },
  {
    id: 14,
    en: `water`,
    yo: `omi`,
    ig: `mmiri`,
    pg: `water`,
    category: "food",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 15,
    en: `rice`,
    yo: `ìrẹsì`,
    ig: `osikapa`,
    pg: `rice`,
    category: "food",
    difficulty: 1,
  },
  {
    id: 16,
    en: `pepper`,
    yo: `ata`,
    ig: `ọse`,
    pg: `pepper`,
    category: "food",
    difficulty: 1,
  },
  {
    id: 17,
    en: `school`,
    yo: `ilé-ìwé`,
    ig: `ụlọ akwụkwọ`,
    pg: `school`,
    category: "school",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 18,
    en: `teacher`,
    yo: `olùkọ́`,
    ig: `onye nkuzi`,
    pg: `teacher`,
    category: "school",
    difficulty: 2, tags: ["kids"],
  },
  {
    id: 19,
    en: `book`,
    yo: `ìwé`,
    ig: `akwụkwọ`,
    pg: `book`,
    category: "school",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 20,
    en: `pen`,
    yo: `kálàmù`,
    ig: `pẹn`,
    pg: `pen`,
    category: "school",
    difficulty: 2,
  },
  {
    id: 21,
    en: `one`,
    yo: `ọ̀kan`,
    ig: `otu`,
    pg: `one`,
    category: "numbers",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 22,
    en: `two`,
    yo: `èjì`,
    ig: `abụọ`,
    pg: `two`,
    category: "numbers",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 23,
    en: `three`,
    yo: `ẹ̀ta`,
    ig: `atọ`,
    pg: `three`,
    category: "numbers",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 24,
    en: `four`,
    yo: `ẹ̀rìn`,
    ig: `anọ`,
    pg: `four`,
    category: "numbers",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 25,
    en: `red`,
    yo: `pupa`,
    ig: `uhie`,
    pg: `red`,
    category: "colors",
    difficulty: 1, tags: ["kids"],
  },
  {
    id: 26,
    en: `blue`,
    yo: `búlúù`,
    ig: `anụnụ anụnụ`,
    pg: `blue`,
    category: "colors",
    difficulty: 2, tags: ["kids"],
  },
  {
    id: 27,
    en: `come`,
    yo: `wá`,
    ig: `bịa`,
    pg: `come`,
    category: "actions",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 28,
    en: `go`,
    yo: `lọ`,
    ig: `gaa`,
    pg: `go`,
    category: "actions",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 29,
    en: `stop`,
    yo: `dúró`,
    ig: `kwụsị`,
    pg: `stop`,
    category: "actions",
    difficulty: 1, tags: ["daily"],
  },
  {
    id: 30,
    en: `where is it?`,
    yo: `ǹibo ni?`,
    ig: `ọ dị ebee?`,
    pg: `where e dey?`,
    category: "travel",
    difficulty: 2, tags: ["daily"],
  },
  {
    id: 31,
    en: `i am tired`,
    yo: `mo rẹ́`,
    ig: `ike gwụrụ m`,
    pg: `i dey tired`,
    category: "health",
    difficulty: 2, tags: ["daily"],
  },
  {
    id: 32,
    en: `i am fine`,
    yo: `mo wà dáadáa`,
    ig: `adị m mma`,
    pg: `i dey okay`,
    category: "health",
    difficulty: 2, tags: ["daily"],
  },
  {
    id: 100,
    en: `test word`,
    yo: `àdánwò`,
    ig: `nnwale`,
    pg: `test`,
    category: "school",
    difficulty: 1, tags: ["dev","test"], notes: {"yo":"dev/test row"},
  },
];
