/* eslint-disable */
// scripts/generate_audiomap.mjs
// Scans assets/audio/<lang>/<id>.mp3 and writes app/data/audiomap.generated.ts
// IMPORTANT: Skips placeholder mp3s by comparing to assets/audio/_placeholders/<lang>.placeholder.mp3

import fs from "fs";
import path from "path";
import crypto from "crypto";

const ROOT = process.cwd();

const AUDIO_DIR = path.join(ROOT, "assets", "audio");
const OUT_FILE = path.join(ROOT, "app", "data", "audiomap.generated.ts");

const LANGS = ["yo", "ig", "pg"];

function sha1File(filePath) {
  const buf = fs.readFileSync(filePath);
  return crypto.createHash("sha1").update(buf).digest("hex");
}

function loadPlaceholderSig(lang) {
  const p = path.join(AUDIO_DIR, "_placeholders", `${lang}.placeholder.mp3`);
  if (!fs.existsSync(p)) return null;
  try {
    const stat = fs.statSync(p);
    const hash = sha1File(p);
    return { size: stat.size, hash };
  } catch {
    return null;
  }
}

function isNumericMp3(name) {
  return /^\d+\.mp3$/i.test(name);
}

function relToAppDataRequire(absFilePath) {
  // app/data/audiomap.generated.ts requires "../../assets/audio/yo/1.mp3"
  const rel = path.relative(path.join(ROOT, "app", "data"), absFilePath).replace(/\\/g, "/");
  return rel.startsWith(".") ? rel : `./${rel}`;
}

function main() {
  const placeholder = Object.fromEntries(LANGS.map((l) => [l, loadPlaceholderSig(l)]));

  const entries = [];

  for (const lang of LANGS) {
    const dir = path.join(AUDIO_DIR, lang);
    if (!fs.existsSync(dir)) continue;

    const files = fs.readdirSync(dir);

    for (const f of files) {
      if (!isNumericMp3(f)) continue;

      const abs = path.join(dir, f);

      // Skip placeholder mp3s if we have a fingerprint for this language
      const sig = placeholder[lang];
      if (sig) {
        try {
          const stat = fs.statSync(abs);
          if (stat.size === sig.size) {
            const h = sha1File(abs);
            if (h === sig.hash) {
              continue; // placeholder -> do NOT include in audiomap
            }
          }
        } catch {
          // if we can't read, skip it
          continue;
        }
      }

      const id = f.replace(/\.mp3$/i, "");
      const key = `${lang}/${id}`;
      const reqRel = relToAppDataRequire(abs);

      entries.push({ key, reqRel });
    }
  }

  entries.sort((a, b) => a.key.localeCompare(b.key, "en"));

  const header = `/* eslint-disable */
// app/data/audiomap.generated.ts
// auto-generated by scripts/generate_audiomap.mjs
// DO NOT EDIT BY HAND.

export type AudioLang = "yo" | "ig" | "pg";
export type AudioMap = Record<string, any>;

export const audiomap: AudioMap = {
`;

  const body = entries
    .map((e) => `  "${e.key}": require("${e.reqRel}"),`)
    .join("\n");

  const footer = `
};
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, header + body + footer, "utf8");

  console.log(`✅ Wrote ${OUT_FILE}`);
  console.log(`✅ Entries: ${entries.length}`);
  console.log(
    `ℹ️ Placeholder fingerprints loaded: ` +
      LANGS.map((l) => `${l}=${placeholder[l] ? "YES" : "NO"}`).join(" ")
  );
}

main();
