/* eslint-disable */
// scripts/generate_audiomap.mjs
// Generates app/data/audiomap.generated.ts by scanning assets/audio/<lang>/<id>.mp3
// ✅ Keys: "yo/1", "ig/13", etc.

import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const AUDIO_ROOT = path.join(ROOT, "assets", "audio");
const OUT_PATH = path.join(ROOT, "app", "data", "audiomap.generated.ts");

const LANGS = ["yo", "ig", "pg"];

function isMp3(name) {
  return name.toLowerCase().endsWith(".mp3");
}

function main() {
  const entries = {};

  for (const lang of LANGS) {
    const dir = path.join(AUDIO_ROOT, lang);
    if (!fs.existsSync(dir)) continue;

    const files = fs.readdirSync(dir).filter(isMp3);

    for (const f of files) {
      const base = f.replace(/\.mp3$/i, "");
      // accept numeric ids only
      if (!/^\d+$/.test(base)) continue;

      const key = `${lang}/${base}`;
      // from app/data -> ../../assets/audio/...
      entries[key] = `require("../../assets/audio/${lang}/${base}.mp3")`;
    }
  }

  const keys = Object.keys(entries).sort((a, b) => {
    const [la, ida] = a.split("/");
    const [lb, idb] = b.split("/");
    if (la !== lb) return la.localeCompare(lb);
    return Number(ida) - Number(idb);
  });

  const out = [];
  out.push("/* eslint-disable */");
  out.push("// app/data/audiomap.generated.ts");
  out.push("// auto-generated by scripts/generate_audiomap.mjs");
  out.push("// DO NOT EDIT BY HAND.");
  out.push("");
  out.push('export type AudioLang = "yo" | "ig" | "pg";');
  out.push("export type AudioMap = Record<string, any>;");
  out.push("");
  out.push("export const audiomap: AudioMap = {");

  for (const k of keys) {
    out.push(`  "${k}": ${entries[k]},`);
  }

  out.push("};");
  out.push("");

  fs.writeFileSync(OUT_PATH, out.join("\n"), "utf8");
  console.log(`✅ wrote ${OUT_PATH}`);
  console.log(`✅ Entries: ${keys.length}`);
}

main();
